### ISSUE TITLE
[CBI] Build takes very long and tests timeout

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext-core#1178]
The Gradle Build on CBI takes forever (40 mins) some tests fail due timeouts
https://ci-staging.eclipse.org/xtext/job/xtext-core/job/master/
this is much slower as the CI which is already relatively slow
(compared to a 5 year old thinkpad)

am not sure if the memory is insufficient with ` -Dorg.gradle.daemon=false`
and we need to specify `-Xmx` too.
or the CPU is to few

or CBI is so crappy in general (then we should give up, we will never have any builds)

**Comment by cdietrich** [comment]
cc @Hejado

**Comment by cdietrich** [comment]
https://ci-staging.eclipse.org/xtext/job/xtext-lib/job/master/ is much slower as well

**Comment by cdietrich** [comment]
we also dont specfiy memory for gradle anywhere e.g. via

```gradle.properties
org.gradle.jvmargs=-Xmx2G
```

**Comment by cdietrich** [comment]
cc @fredg02 this is one example of problems we have with CBI

**Comment by cdietrich** [comment]
maybe 1 cpu is too less: https://ci-staging.eclipse.org/xtext/job/xtext-core/job/cd_noGradleCrapOnStaging/

**Comment by Hejado** [comment]
@cdietrich You might not even have 1 cpu, as the default is set 0.25, if I remember correctly. I'd be interested in a comparison of build times with the following scenarios:

* no cpu settings
* cpu setting to 0.25
* cpu setting to 1
* cpu setting to 2

Unfortunately, I cannot yet test this myself :-(

**Comment by cdietrich** [comment]
- with no settings: 40 mins (test is failing / see above)
- with 0.25: 49 mins (test is failing - no idea why this is even worse than with default)
- with 0.5: 31 mins (test is still failing)
- with 1: 31 mins
- with 2: 9 mins (test is green)
=> maybe the default is even worse than 0.25 or there are other factors i dont see.
=> will restart 0.25 and 1 and see if these times are stable

**Comment by cdietrich** [comment]
@Hejado 
how do the jenkinsfiles get picked up.
why is https://ci-staging.eclipse.org/xtext/job/xtext-core/job/cd_noGradleCrapOnStaging025/2/console now 11 mins?

**Comment by cdietrich** [comment]
the log says

```
resources:
      limits:
        memory: "2Gi"
        cpu: "1"
      requests:
        memory: "2Gi"
        cpu: "1"
```

but the code says
https://github.com/eclipse/xtext-core/compare/cd_noGradleCrapOnStaging025

**Comment by cdietrich** [comment]
=>another example is here https://ci-staging.eclipse.org/xtext/job/xtext-core/job/cd_noGradleCrapOnStaging05/4/console

**Comment by Hejado** [comment]
@cdietrich You must not use git force push if you change the Jenkinsfile. Jenkins will get confused and use a cached version, because it cannot detect changes, see here: https://ci-staging.eclipse.org/xtext/job/xtext-core/job/cd_noGradleCrapOnStaging05/changes

**Comment by cdietrich** [comment]
will it ever recover do i need to create new branches?

**Comment by Hejado** [comment]
Change something (add a comment) in Jenkinsfile and do a normal non-ammending commit & push. Should fix it

**Comment by cdietrich** [comment]
pushed new branches cd_issue1178*
lets see what happens

**Comment by fredg02** [comment]
>     * with 0.25: 49 mins (test is failing - no idea why this is even worse than with default)
>     [...]
>       => maybe the default is even worse than 0.25 or there are other factors i dont see.
>       => will restart 0.25 and 1 and see if these times are stable
Default CPU request is 200m => 0.2

**Comment by cdietrich** [comment]
@Hejado still dont get it. here there is no config at all https://ci-staging.eclipse.org/xtext/job/xtext-core/job/cd_issue1178_05/1/console but why.
https://github.com/eclipse/xtext-core/compare/cd_issue1178_05

**Comment by cdietrich** [comment]
new data:
0.25: 30 min
0.5: 15:15 min
1: 8 min
2: 6:15 min

**Comment by kthoms** [comment]
So looks as if we should go with "1". Requesting more only slightly changes performance, while it may block jobs from being scheduled. IIRC there are only 2 CPUs for all jobs.

**Comment by cdietrich** [comment]
@Hejado can you please prepare PRs for this?

**Comment by Hejado** [comment]
Sure. Will start very soon

**Comment by Hejado** [comment]
Only added cpu, not memory (if not present), to not mess with [eclipse/xtext#1431]

**Comment by cdietrich** [comment]
we set the  cpu, but it seems that the pod config that is picked is random. see https://github.com/eclipse/xtext/issues/1495

**Comment by cdietrich** [comment]
Memory looks good now
